/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Items */
        get: operations["read_items_items__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Item */
        get: operations["read_item_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Transcript
         * @description Process a transcript file and extract structured information using Gemini AI.
         *
         *     This endpoint accepts either a .txt or .pdf file containing a meeting transcript,
         *     sends it directly to the Gemini API for analysis (Gemini handles text extraction),
         *     and returns structured information including:
         *     - Meeting summary
         *     - Participants
         *     - Key topics discussed
         *     - Action items
         *     - Next steps
         *
         *     Args:
         *         file: The uploaded transcript file (.txt or .pdf)
         *         settings: Application settings (injected)
         *         gemini_client: Gemini API client (injected)
         *
         *     Returns:
         *         TranscriptProcessResponse: Structured analysis of the transcript
         *
         *     Raises:
         *         HTTPException: If file validation fails or processing errors occur
         */
        post: operations["process_transcript_transcripts_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcripts/upload_tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Transcript Tasks
         * @description Upload extracted tasks from the transcript to Microsoft Planner
         *
         *     Args:
         *         extracted_tasks: The structured tasks extracted from the transcript
         *         planner_service: Microsoft Planner service (injected)
         */
        post: operations["upload_transcript_tasks_transcripts_upload_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_process_transcript_transcripts_process_post */
        Body_process_transcript_transcripts_process_post: {
            /**
             * File
             * Format: binary
             * @description Transcript file (.txt or .pdf)
             */
            file: string;
            /**
             * Meeting Details
             * @description JSON string with meeting details
             */
            meeting_details: string;
        };
        /** CheckListItem */
        CheckListItem: {
            /**
             * Title
             * @description Checklist item description
             */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MeetingDetails
         * @description Metadata about the meeting transcript
         */
        MeetingDetails: {
            /**
             * Meeting Title
             * @description Title or subject of the meeting
             */
            meeting_title?: string | null;
            /**
             * Meeting Date
             * @description Date of the meeting in ISO 8601 format
             */
            meeting_date?: string | null;
        };
        /**
         * MeetingExtractionResult
         * @description Complete extraction result from meeting transcription
         */
        "MeetingExtractionResult-Input": {
            /** @description Metadata about the meeting */
            meeting_details: components["schemas"]["MeetingDetails"];
            /**
             * Task Groups
             * @description Groups of tasks associated with plans
             */
            task_groups: components["schemas"]["TaskGroup-Input"][];
            /**
             * Action Items Count
             * @description Total number of action items extracted from the meeting
             * @default 0
             */
            action_items_count: number;
            /**
             * Meeting Date
             * @description Date of the meeting in ISO 8601 format
             */
            meeting_date?: string | null;
            /**
             * Meeting Summary
             * @description Brief summary of the meeting
             */
            meeting_summary?: string | null;
        };
        /**
         * MeetingExtractionResult
         * @description Complete extraction result from meeting transcription
         */
        "MeetingExtractionResult-Output": {
            /** @description Metadata about the meeting */
            meeting_details: components["schemas"]["MeetingDetails"];
            /**
             * Task Groups
             * @description Groups of tasks associated with plans
             */
            task_groups: components["schemas"]["TaskGroup-Output"][];
            /**
             * Action Items Count
             * @description Total number of action items extracted from the meeting
             * @default 0
             */
            action_items_count: number;
            /**
             * Meeting Date
             * @description Date of the meeting in ISO 8601 format
             */
            meeting_date?: string | null;
            /**
             * Meeting Summary
             * @description Brief summary of the meeting
             */
            meeting_summary?: string | null;
        };
        /**
         * PlanAssociation
         * @description Associates tasks with a plan (existing or new)
         */
        PlanAssociation: {
            /** @description Whether to use existing plan or create new one */
            association_type: components["schemas"]["PlanAssociationType"];
            /**
             * Plan Title
             * @description Title for new plan OR matched title for existing plan
             */
            plan_title: string;
            /** @description Reference to existing plan (required if association_type is 'existing') */
            plan_reference?: components["schemas"]["PlanReference"] | null;
            /**
             * Rationale
             * @description Explanation for why this plan was chosen or should be created
             */
            rationale?: string | null;
        };
        /**
         * PlanAssociationType
         * @description How the task relates to a plan
         * @enum {string}
         */
        PlanAssociationType: "existing" | "new";
        /**
         * PlanReference
         * @description Reference to an existing plan
         */
        PlanReference: {
            /**
             * Plan Id
             * @description ID of the existing plan
             */
            plan_id: string;
            /**
             * Plan Title
             * @description Title of the existing plan
             */
            plan_title: string;
            /**
             * Confidence Score
             * @description Confidence score for the match (0.0 to 1.0)
             */
            confidence_score: number;
        };
        /**
         * TaskAssignment
         * @description Assignment information for a task
         */
        TaskAssignment: {
            /**
             * Assignee Name
             * @description Full name of the person assigned
             */
            assignee_name: string;
            /**
             * Assignee Email
             * @description Email address if mentioned
             */
            assignee_email?: string | null;
        };
        /**
         * TaskDetails
         * @description Detailed information about a task extracted from the meeting
         */
        TaskDetails: {
            /**
             * Description
             * @description Detailed description of the task
             */
            description: string;
            /**
             * Checklist Items
             * @description Checklist items for the task
             */
            checklist_items?: components["schemas"]["CheckListItem"][];
        };
        /**
         * TaskGroup
         * @description Group of related tasks associated with a plan
         */
        "TaskGroup-Input": {
            /** @description Plan to associate these tasks with */
            plan_association: components["schemas"]["PlanAssociation"];
            /**
             * Tasks
             * @description list of tasks in this group
             */
            tasks: components["schemas"]["TranscriptionTask-Input"][];
            /**
             * Group Description
             * @description Context about why these tasks are grouped together
             */
            group_description?: string | null;
        };
        /**
         * TaskGroup
         * @description Group of related tasks associated with a plan
         */
        "TaskGroup-Output": {
            /** @description Plan to associate these tasks with */
            plan_association: components["schemas"]["PlanAssociation"];
            /**
             * Tasks
             * @description list of tasks in this group
             */
            tasks: components["schemas"]["TranscriptionTask-Output"][];
            /**
             * Group Description
             * @description Context about why these tasks are grouped together
             */
            group_description?: string | null;
        };
        /**
         * TaskPriority
         * @description Priority levels for tasks (0-10 scale in Planner)
         * @enum {string}
         */
        TaskPriority: "1" | "3" | "5" | "9";
        /** TranscriptionTask */
        "TranscriptionTask-Input": {
            /** @description Details of the task */
            details: components["schemas"]["TaskDetails"];
            /**
             * Assignments
             * @description People assigned to this task
             */
            assignments?: components["schemas"]["TaskAssignment"][];
            /**
             * Due Date
             * @description Due date in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
             */
            due_date?: string | null;
            /**
             * Title
             * @description Clear, concise task title
             */
            title: string;
            /**
             * Startdatetime
             * @description Start date in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
             */
            startDateTime?: string | null;
            /**
             * @description Task priority level
             * @default 5
             */
            priority: components["schemas"]["TaskPriority"];
        };
        /** TranscriptionTask */
        "TranscriptionTask-Output": {
            /** @description Details of the task */
            details: components["schemas"]["TaskDetails"];
            /**
             * Assignments
             * @description People assigned to this task
             */
            assignments?: components["schemas"]["TaskAssignment"][];
            /**
             * Due Date
             * @description Due date in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
             */
            due_date?: string | null;
            /**
             * Title
             * @description Clear, concise task title
             */
            title: string;
            /**
             * Startdatetime
             * @description Start date in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
             */
            startDateTime?: string | null;
            /**
             * @description Task priority level
             * @default 5
             */
            priority: components["schemas"]["TaskPriority"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_items_items__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_item_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_transcript_transcripts_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_process_transcript_transcripts_process_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingExtractionResult-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_transcript_tasks_transcripts_upload_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingExtractionResult-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
